name: My Workflow  # Name of your workflow

on:
  push:
    branches:
      - main  # Trigger workflow on push events to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Operating system environment for the job

    steps:
      - name: Checkout code  # Name of the step
        uses: actions/checkout@v2  # Action to checkout the repository

      - name: Set up Node.js  # Name of the step
        uses: actions/setup-node@v2  # Action to set up Node.js
        with:
          node-version: '20'  # Version of Node.js to use

      - name: Install dependencies  # Name of the step
        run: npm install  # Command to run

      - name: Run tests  # Name of the step
        run: npm test  # Command to run

      - name: Deploy to production  # Name of the step
        if: success() && github.event_name == 'push'  # Conditional step based on success and event type
        run: |
          echo Deploying to production...
          # Your deployment script or commands here
